# Generated by Django 3.1.1 on 2020-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
